http:
  routers:
    traefik:
      rule: "Host(`traefik.docker.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "localhost"
          - main: "127.0.0.1"
          - main: "docker.localhost"
            sans:
              - "*.docker.localhost"
          - main: "api.localhost"
          - main: "app.localhost"

tls:
  certificates:
    - certFile: "/etc/certificates/cert.pem"
      keyFile: "/etc/certificates/key.pem"
